title: Chris Jennings at Brookes
description: A website with a blog
footer_text: Copyright 2021 Chris Jennings
header_feature_image: ../uploads/oxford_fromtheparkcropped.jpg
header_text: Oxford Digital Dreams
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: ../uploads/cjhhhinitials.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
